{"name": "Ошибка при попытке повторного создания существующего пользователя", "status": "passed", "start": 1718881362599, "stop": 1718881363425, "uuid": "861d6466-7ca9-4667-8e67-33bdb4633e11", "historyId": "28ee5c50acb04a591087da2c11df6756", "testCaseId": "28ee5c50acb04a591087da2c11df6756", "fullName": "tests.test_create_user.TestCreateUser#test_register_double_user_failed_result", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_create_user"}, {"name": "subSuite", "value": "TestCreateUser"}, {"name": "host", "value": "LAPTOP-8BB0DG15"}, {"name": "thread", "value": "19632-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_user"}]}